<a href="https://colab.research.google.com/github/megnaanand/climate-change-analysis/blob/main/climate_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import pandas as pd

## 1. Introduction

This data exploration and inference project aims to uncover correlations between environmental changes and a global rise in temperatures over the years 1880 to 2020, utilizing datasets provided by NASA Climate Change.

### 1.1. Project Overview
Briefly describe the project's goals and significance.

### 1.2. Scope of the Project
Define the specific aspects of climate change being studied.

### 1.3. Data Sources
Introduce NASA datasets being used (CO2 and Methane levels, Global Temperature, etc.).

### 1.4. Importance of the Study
Discuss the relevance of understanding climate change indicators.

## 2. Data Collection and Preprocessing
 We will be using  information about global Carbon Dioxide and Methane levels, Global Temperature, Ocean Warming, Ice Sheets Sea Levels, and Arctic Sea Ice levels.

### 2.1. Data Collection
Load the datasets from NASA

In [50]:
df_ice_sheets = pd.read_csv("data/ice_sheets.txt", delim_whitespace=True)
df_ice_sheets['TIME(year.decimal)'] = df_ice_sheets['TIME(year.decimal)'].astype(int)
df_ice_sheets = df_ice_sheets.groupby('TIME(year.decimal)').mean().reset_index()
df_ice_sheets = df_ice_sheets.rename(columns={'TIME(year.decimal)': 'Year'})
print(df_ice_sheets)

    Year  Antarctic-mass(Gigatonnes)  \
0   2002                   -7.431429
1   2003                 -114.470000
2   2004                 -260.975000
3   2005                 -227.801667
4   2006                 -129.412500
5   2007                 -315.981667
6   2008                 -586.281667
7   2009                 -562.995833
8   2010                 -841.445833
9   2011                 -940.604444
10  2012                -1075.557273
11  2013                -1286.856667
12  2014                -1498.881111
13  2015                -1850.552222
14  2016                -1775.763333
15  2017                -1818.544000
16  2018                -2129.990000
17  2019                -2326.797500
18  2020                -2557.049167
19  2021                -2638.302500
20  2022                -2438.013333
21  2023                -2329.820000

    Antarctic-mass-1-sigma-uncertainty(Gigatonnes)
0                                        91.620000
1                                        44.167273
2                                        37.161667
3                                        34.594167
4                                        36.380000
5                                        38.661667
6                                        40.555000
7                                        36.072500
8                                        35.743333
9                                        40.820000
10                                       39.519091
11                                       38.198889
12                                       33.766667
13                                       37.300000
14                                       41.070000
15                                       60.672000
16                                       30.290000
17                                       26.829167
18                                       26.781667
19                                       26.724167
20                                       28.221667
21                                       45.351667

In [51]:
df_c02_levels = pd.read_csv("data/c02_levels.txt", delim_whitespace=True)
df_c02_levels = df_c02_levels.groupby('date').mean().reset_index()
df_c02_levels = df_c02_levels.rename(columns={'date': 'Year'})
print(df_c02_levels)

    Year  month  decimal-date  monthly-avg  de-season-alized       days  \
0   1958    7.5   1958.580000   315.232000        315.292000  -1.000000
1   1959    6.5   1959.497258   315.980833        315.977500  -1.000000
2   1960    6.5   1960.498192   316.910000        316.907500  -1.000000
3   1961    6.5   1961.497258   317.644167        317.640833  -1.000000
4   1962    6.5   1962.497258   318.454167        318.448333  -1.000000
..   ...    ...           ...          ...               ...        ...
61  2019    6.5   2019.500000   411.649167        411.650000  27.666667
62  2020    6.5   2020.500000   414.210833        414.210833  28.000000
63  2021    6.5   2021.500000   416.413333        416.414167  28.000000
64  2022    6.5   2022.500000   418.528333        418.527500  27.916667
65  2023    5.5   2023.416670   421.064000        420.783000  25.900000

    st-dev-days  unc-of-mon-mean
0     -9.990000        -0.990000
1     -9.990000        -0.990000
2     -9.990000        -0.990000
3     -9.990000        -0.990000
4     -9.990000        -0.990000
..          ...              ...
61     0.630833         0.230833
62     0.508333         0.185000
63     0.659167         0.240000
64     0.586667         0.212500
65     0.540000         0.203000

[66 rows x 8 columns]

In [52]:
df_global_temperatures = pd.read_csv("data/global_temperatures.txt", delim_whitespace=True)
print(df_global_temperatures)

     Year  No_Smoothing  Lowess(5)
0    1880         -0.17      -0.10
1    1881         -0.09      -0.13
2    1882         -0.11      -0.17
3    1883         -0.18      -0.21
4    1884         -0.29      -0.24
..    ...           ...        ...
138  2018          0.85       0.93
139  2019          0.97       0.92
140  2020          1.01       0.91
141  2021          0.84       0.91
142  2022          0.89       0.90

[143 rows x 3 columns]

In [53]:
df_methane = pd.read_csv("data/methane.txt", delim_whitespace=True)
df_methane = df_methane.rename(columns={'year': 'Year'})
print(df_methane)

    Year     mean   unc
0   1984  1644.85  0.67
1   1985  1657.29  0.59
2   1986  1670.09  0.74
3   1987  1682.70  0.49
4   1988  1693.16  0.67
5   1989  1704.53  0.55
6   1990  1714.43  0.68
7   1991  1724.82  0.72
8   1992  1735.47  0.57
9   1993  1736.50  0.46
10  1994  1742.07  0.58
11  1995  1748.88  0.48
12  1996  1751.28  0.68
13  1997  1754.53  0.42
14  1998  1765.54  0.64
15  1999  1772.34  0.64
16  2000  1773.33  0.81
17  2001  1771.22  0.59
18  2002  1772.66  0.55
19  2003  1777.33  0.50
20  2004  1777.05  0.50
21  2005  1774.16  0.64
22  2006  1774.95  0.56
23  2007  1781.37  0.63
24  2008  1787.01  0.77
25  2009  1793.53  0.69
26  2010  1798.93  0.73
27  2011  1803.14  0.63
28  2012  1808.12  0.63
29  2013  1813.41  0.66
30  2014  1822.57  0.53
31  2015  1834.26  0.55
32  2016  1843.12  0.68
33  2017  1849.58  0.64
34  2018  1857.33  0.82
35  2019  1866.58  0.60
36  2020  1878.93  0.56
37  2021  1895.28  0.55
38  2022  1911.82  0.78

In [54]:
df_sea_levels = pd.read_csv("data/sea_levels.txt", delim_whitespace=True)
df_sea_levels['year_fraction_of_year'] = df_sea_levels['year_fraction_of_year'].astype(int)
df_sea_levels = df_sea_levels.groupby('year_fraction_of_year').mean().reset_index()
df_sea_levels = df_sea_levels.rename(columns={'year_fraction_of_year': 'Year'})
print(df_sea_levels)

    Year  altimeter_type  merged_file_cycle_#  number_of_observations  \
0   1993           81.00            29.000000           438921.432432
1   1994           81.00            66.000000           445283.621622
2   1995          135.00           103.000000           437328.135135
3   1996           83.25           139.500000           445291.527778
4   1997          108.00           176.000000           442118.918919
5   1998          108.00           213.000000           439315.459459
6   1999          108.00           250.000000           436719.648649
7   2000           81.00           287.000000           439614.378378
8   2001           27.00           324.000000           444132.081081
9   2002            0.00           360.500000           453726.305556
10  2003            0.00           397.000000           445957.945946
11  2004            0.00           434.000000           447351.918919
12  2005            0.00           471.000000           448167.027027
13  2006            0.00           507.638889           448540.333333
14  2007            0.00           545.000000           459204.432432
15  2008            0.00           581.500000           449792.777778
16  2009            0.00           618.000000           454362.486486
17  2010            0.00           655.000000           457906.216216
18  2011            0.00           692.000000           459534.837838
19  2012            0.00           729.000000           458978.810811
20  2013            0.00           766.000000           434411.027027
21  2014            0.00           802.500000           455886.055556
22  2015            0.00           839.000000           457122.837838
23  2016            0.00           876.000000           457075.540541
24  2017            0.00           913.000000           460470.513514
25  2018            0.00           950.000000           460140.054054
26  2019            0.00           987.000000           439841.027027
27  2020            0.00          1023.500000           436136.638889
28  2021            0.00          1060.000000           459071.756757
29  2022            0.00          1097.000000           459525.621622
30  2023            0.00          1125.500000           464334.050000

    number_weighted_observations  GMSL_no_GIA_mm  \
0                  319119.098108      -34.625676
1                  323836.834054      -30.970270
2                  317986.153784      -28.662973
3                  323979.220556      -26.613611
4                  321345.544324      -22.696216
5                  320066.637297      -25.075405
6                  318321.071081      -21.820811
7                  320497.246216      -18.434054
8                  323101.705676      -13.230541
9                  329781.401944       -9.380000
10                 324636.768649       -6.321622
11                 325639.219730       -4.430270
12                 326065.325676       -0.030811
13                 326130.479444        1.093889
14                 334325.974865        1.489730
15                 327961.544444        3.552500
16                 331113.277297        8.415405
17                 334573.513784        9.398108
18                 334977.921081        8.438108
19                 334590.131622       19.264595
20                 317516.552973       21.315946
21                 332957.143056       24.862778
22                 333484.379189       35.436486
23                 332462.806757       37.478649
24                 335161.481892       38.332973
25                 334988.900811       42.260811
26                 319767.797297       49.165676
27                 317738.229167       49.711111
28                 334512.527297       53.933784
29                 334857.549730       56.301892
30                 335387.547500       57.224500

    standard_deviation_GMSL_no_GIA_mm  smoothed_GMSL_no_GIA  GMSL_GIA_mm  \
0                           87.608919         -3.465000e+01   -34.504054
1                           87.426216         -3.091865e+01   -30.604054
2                           85.356757         -2.798703e+01   -28.038108
3                           84.227222         -2.615806e+01   -25.761111
4                           98.027027         -2.236162e+01   -21.605946
5                           96.181892         -2.498108e+01   -23.741081
6                           86.728649         -2.161919e+01   -20.236486
7                           85.911081         -1.861432e+01   -16.607027
8                           83.910811         -1.328919e+01   -11.156486
9                           85.393056         -9.390556e+00    -7.065833
10                          86.547297         -6.264324e+00    -3.766757
11                          85.545135         -4.550811e+00    -1.627568
12                          84.578108         -6.001206e-18     3.014054
13                          85.335833          1.115833e+00     4.375000
14                          84.649189          1.568649e+00     5.024054
15                          86.268333          3.503611e+00     7.331944
16                          84.531622          8.367568e+00    12.434865
17                          86.690541          9.426486e+00    13.661622
18                          87.350811          8.530541e+00    12.944595
19                          84.558378          1.917892e+01    24.011622
20                          84.447838          2.135324e+01    26.309189
21                          84.503889          2.477250e+01    30.091111
22                          94.597838          3.551351e+01    40.910541
23                          90.919459          3.743622e+01    43.196486
24                          84.585405          3.833514e+01    44.297568
25                          86.053243          4.231973e+01    48.465946
26                          87.808649          4.906405e+01    55.612162
27                          87.150556          4.984528e+01    56.413333
28                          87.137297          5.392595e+01    60.873514
29                          88.444324          5.620054e+01    63.486216
30                          86.311500          5.710400e+01    64.598000

    standard_deviation_GMSL_GIA_mm  smoothed_GMSL_GIA_mm  \
0                        87.612432            -34.528108
1                        87.432162            -30.552432
2                        85.357297            -27.376486
3                        84.221944            -25.305556
4                        98.040541            -21.270811
5                        96.184324            -23.648378
6                        86.704054            -20.036216
7                        85.911081            -16.787297
8                        83.949189            -11.213784
9                        85.449444             -7.076667
10                       86.612703             -3.708919
11                       85.564865             -1.749189
12                       84.549730              3.044595
13                       85.337222              4.396944
14                       84.635135              5.103514
15                       86.246111              7.282778
16                       84.568378             12.387297
17                       86.701351             13.690811
18                       87.350811             13.036757
19                       84.598378             23.925405
20                       84.470000             26.346486
21                       84.702500             30.000833
22                       94.895135             40.987297
23                       91.112703             43.153243
24                       84.826486             44.298919
25                       86.218378             48.524865
26                       88.024054             55.510270
27                       87.258611             56.546667
28                       87.179189             60.865135
29                       88.608108             63.385405
30                       86.308500             64.477000

    smoothed_GMSL_GIA_annual_semi_removed_mm  \
0                                 -34.528108
1                                 -30.551892
2                                 -27.375405
3                                 -25.304722
4                                 -21.271622
5                                 -23.648649
6                                 -20.035946
7                                 -16.786757
8                                 -11.212432
9                                  -7.076111
10                                 -3.710270
11                                 -1.749189
12                                  3.044054
13                                  4.507778
14                                  5.104595
15                                  7.283056
16                                 12.386486
17                                 13.690000
18                                 13.037297
19                                 23.925946
20                                 26.346757
21                                 30.001389
22                                 40.986757
23                                 43.153243
24                                 44.298649
25                                 48.525405
26                                 55.511351
27                                 56.547778
28                                 60.864595
29                                 63.384324
30                                 66.915000

    smoothed_GMSL_no_GIA_annual_semi_removed_mm
0                                    -34.649459
1                                    -30.918108
2                                    -27.986216
3                                    -26.157222
4                                    -22.363514
5                                    -24.982162
6                                    -21.618919
7                                    -18.614054
8                                    -13.287838
9                                     -9.390278
10                                    -6.265135
11                                    -4.551081
12                                     0.000000
13                                     1.227222
14                                     1.568919
15                                     3.504444
16                                     8.366216
17                                     9.426486
18                                     8.529730
19                                    19.178108
20                                    21.353784
21                                    24.772778
22                                    35.512703
23                                    37.435946
24                                    38.335135
25                                    42.319730
26                                    49.064865
27                                    49.846389
28                                    53.924595
29                                    56.199459

30                                    59.542500

In [55]:
df_ocean_warming = pd.read_json("data/ocean_warming.json", orient='index')
df_ocean_warming.reset_index(inplace=True)
df_ocean_warming.columns = ['Year', 'Data']
df_ocean_warming['Year'] = pd.to_datetime(df_ocean_warming['Year']).dt.year
df_ocean_warming['Year'] = df_ocean_warming['Year'].astype(int)
df_ocean_warming = df_ocean_warming.groupby('Year').mean().reset_index()
print(df_ocean_warming)

    Year        Data
0   1992  -10.881634
1   1993  -13.388852
2   1994   -2.664185
3   1995    5.064039
4   1996   15.332920
5   1997   28.435488
6   1998   32.686694
7   1999   35.310359
8   2000   42.600858
9   2001   57.759469
10  2002   63.085198
11  2003   69.738707
12  2004   76.696781
13  2005   79.527011
14  2006   84.202106
15  2007   85.001658
16  2008   86.782922
17  2009   97.720881
18  2010   95.914445
19  2011   98.463361
20  2012  106.762859
21  2013  115.860755
22  2014  122.539245
23  2015  130.726140
24  2016  134.756371
25  2017  143.245331
26  2018  160.595839
27  2019  181.744261

In [56]:
df_arctic_sea_ice = pd.read_excel("data/arctic_sea_ice.xlsx", index_col=0)

print(df_arctic_sea_ice)

      January  February   March   April     May    June    July  August  \
Year
1978      NaN       NaN     NaN     NaN     NaN     NaN     NaN     NaN
1979   15.414    16.175  16.342  15.447  13.857  12.530  10.311   8.041
1980   14.862    15.955  16.041  15.429  13.793  12.205  10.100   7.984
1981   14.910    15.604  15.632  15.010  13.802  12.430  10.271   7.844
1982   15.177    15.974  16.044  15.466  13.973  12.476  10.367   8.139
1983   14.942    16.006  16.085  15.172  13.491  12.296  10.570   8.186
1984   14.473    15.299  15.584  15.015  13.577  12.152   9.977   7.771
1985   14.725    15.466  15.886  15.357  14.073  12.219   9.744   7.402
1986   14.890    15.785  15.910  15.059  13.379  11.976  10.146   7.979
1987   14.970    16.050  15.816  15.211  13.743  12.486  10.333   7.628
1988      NaN    15.583  15.957  15.123  13.561  11.943   9.809   7.892
1989   14.955    15.495  15.423  14.328  13.044  12.245  10.130   7.882
1990   14.783    15.578  15.867  14.650  13.226  11.641   9.247   6.797
1991   14.364    15.249  15.416  14.860  13.473  12.108   9.514   7.415
1992   14.643    15.462  15.481  14.677  13.216  12.147  10.323   7.925
1993   14.896    15.686  15.813  15.077  13.368  11.871   9.476   7.335
1994   14.730    15.562  15.554  14.888  13.624  12.016   9.925   7.639
1995   14.586    15.226  15.260  14.449  12.972  11.440   8.987   6.744
1996   14.181    15.155  15.123  14.216  13.094  12.084  10.164   8.180
1997   14.417    15.437  15.467  14.563  13.177  11.738   9.411   7.285
1998   14.721    15.746  15.598  14.892  13.590  11.706   9.415   7.509
1999   14.359    15.309  15.398  15.084  13.751  11.779   9.488   7.226
2000   14.220    15.141  15.225  14.558  13.153  11.665   9.513   7.168
2001   14.203    15.211  15.516  14.857  13.510  11.456   9.070   7.461
2002   14.273    15.342  15.349  14.299  12.971  11.583   9.274   6.599
2003   14.391    15.193  15.485  14.512  13.016  11.604   9.215   6.936
2004   14.026    14.914  14.993  13.987  12.558  11.447   9.431   6.855
2005   13.661    14.373  14.687  14.090  12.911  11.162   8.649   6.301
2006   13.466    14.325  14.421  13.906  12.517  10.920   8.460   6.496
2007   13.703    14.513  14.542  13.845  12.780  11.220   7.943   5.342
2008   13.887    14.953  15.179  14.352  12.974  11.208   8.678   5.913
2009   13.914    14.812  14.984  14.496  13.187  11.320   8.465   6.136
2010   13.739    14.581  15.137  14.659  12.866  10.585   8.075   5.875
2011   13.464    14.363  14.546  14.108  12.681  10.749   7.724   5.503
2012   13.729    14.553  15.196  14.626  13.012  10.674   7.672   4.723
2013   13.703    14.723  15.032  14.299  12.997  11.360   8.132   6.014
2014   13.648    14.418  14.758  14.088  12.701  11.033   8.108   6.078
2015   13.602    14.401  14.370  13.893  12.468  10.879   8.378   5.599
2016   13.457    14.203  14.400  13.681  11.924  10.413   7.938   5.371
2017   13.190    14.120  14.290  13.753  12.631  10.756   7.939   5.481
2018   13.077    13.967  14.298  13.696  12.232  10.778   8.268   5.615
2019   13.567    14.394  14.574  13.434  12.186  10.594   7.589   5.026
2020   13.636    14.642  14.730  13.621  12.343  10.593   7.294   5.070
2021   13.501    14.390  14.658  13.792  12.682  10.765   7.647   5.715
2022   13.872    14.612  14.586  13.986  12.879  10.875   8.287   5.950
2023   13.346    14.176  14.440  13.992  12.835  10.963   8.183   5.566

      September  October  November  December  Annual
Year
1978        NaN      NaN    11.645    13.667  12.673
1979      7.051    8.748    10.943    13.336  12.328
1980      7.667    9.183    11.383    13.593  12.337
1981      7.138    8.856    10.929    13.341  12.127
1982      7.302    9.421    11.627    13.642  12.447
1983      7.395    9.334    11.461    13.299  12.332
1984      6.805    8.561    10.842    12.989  11.910
1985      6.698    8.546    11.025    13.050  11.995
1986      7.411    9.484    11.453    13.222  12.203
1987      7.279    9.049    11.224       NaN  12.135
1988      7.369    9.135    11.331    13.626  11.923
1989      7.008    8.829    11.115    13.387  11.967
1990      6.143    8.485    11.075    13.106  11.694
1991      6.473    8.541    10.885    12.945  11.749
1992      7.474    9.319    11.379    13.407  12.110
1993      6.397    8.786    11.319    13.319  11.923
1994      7.138    8.915    11.123    13.272  12.011
1995      6.080    7.829    10.761    12.921  11.415
1996      7.583    9.161    10.402    12.861  11.841
1997      6.686    8.337    10.684    13.076  11.668
1998      6.536    8.452    10.441    12.759  11.757
1999      6.117    8.603    10.796    12.641  11.691
2000      6.246    8.379    10.321    12.637  11.508
2001      6.732    8.298    10.658    12.491  11.600
2002      5.827    8.162    10.342    12.608  11.363
2003      6.116    7.848    10.125    12.588  11.397
2004      5.984    7.925    10.343    12.554  11.240
2005      5.504    7.352    10.216    12.228  10.907
2006      5.862    7.541     9.659    11.955  10.773
2007      4.267    6.040     9.760    12.034  10.474
2008      4.687    7.350    10.343    12.359  10.978
2009      5.262    6.920     9.772    12.200  10.932
2010      4.865    6.984     9.614    11.831  10.711
2011      4.561    6.465     9.772    12.154  10.483
2012      3.566    5.886     9.388    12.006  10.406
2013      5.208    7.455     9.939    12.184  10.897
2014      5.220    7.232    10.115    12.353  10.790
2015      4.616    6.966     9.846    12.045  10.566
2016      4.528    6.082     8.658    11.459  10.163
2017      4.822    6.767     9.493    11.743  10.393
2018      4.785    6.134     9.823    11.862  10.355
2019      4.364    5.735     9.353    11.903  10.201
2020      4.001    5.334     8.985    11.729  10.150
2021      4.952    6.816     9.830    12.152  10.552
2022      4.897    6.657     9.725    11.892  10.661
2023      4.371    6.367       NaN       NaN  10.393

In [58]:
merged_df = pd.merge(df_ice_sheets, df_global_temperatures, on='Year', how='outer')
merged_df = pd.merge(merged_df, df_methane, on='Year', how='outer')
merged_df = pd.merge(merged_df, df_sea_levels, on='Year', how='outer')
merged_df = pd.merge(merged_df, df_ocean_warming, on='Year', how='outer')
merged_df = pd.merge(merged_df, df_arctic_sea_ice, on='Year', how='outer')
merged_df = merged_df.sort_values(by='Year')
print(merged_df)

    Year  Antarctic-mass(Gigatonnes)  \
22  1880                         NaN
23  1881                         NaN
24  1882                         NaN
25  1883                         NaN
26  1884                         NaN
..   ...                         ...
17  2019                -2326.797500
18  2020                -2557.049167
19  2021                -2638.302500
20  2022                -2438.013333
21  2023                -2329.820000

    Antarctic-mass-1-sigma-uncertainty(Gigatonnes)  No_Smoothing  Lowess(5)  \
22                                             NaN         -0.17      -0.10
23                                             NaN         -0.09      -0.13
24                                             NaN         -0.11      -0.17
25                                             NaN         -0.18      -0.21
26                                             NaN         -0.29      -0.24
..                                             ...           ...        ...
17                                       26.829167          0.97       0.92
18                                       26.781667          1.01       0.91
19                                       26.724167          0.84       0.91
20                                       28.221667          0.89       0.90
21                                       45.351667           NaN        NaN

       mean   unc  altimeter_type  merged_file_cycle_#  \
22      NaN   NaN             NaN                  NaN
23      NaN   NaN             NaN                  NaN
24      NaN   NaN             NaN                  NaN
25      NaN   NaN             NaN                  NaN
26      NaN   NaN             NaN                  NaN
..      ...   ...             ...                  ...
17  1866.58  0.60             0.0                987.0
18  1878.93  0.56             0.0               1023.5
19  1895.28  0.55             0.0               1060.0
20  1911.82  0.78             0.0               1097.0
21      NaN   NaN             0.0               1125.5

    number_of_observations  ...   April     May    June   July  August  \
22                     NaN  ...     NaN     NaN     NaN    NaN     NaN
23                     NaN  ...     NaN     NaN     NaN    NaN     NaN
24                     NaN  ...     NaN     NaN     NaN    NaN     NaN
25                     NaN  ...     NaN     NaN     NaN    NaN     NaN
26                     NaN  ...     NaN     NaN     NaN    NaN     NaN
..                     ...  ...     ...     ...     ...    ...     ...
17           439841.027027  ...  13.434  12.186  10.594  7.589   5.026
18           436136.638889  ...  13.621  12.343  10.593  7.294   5.070
19           459071.756757  ...  13.792  12.682  10.765  7.647   5.715
20           459525.621622  ...  13.986  12.879  10.875  8.287   5.950
21           464334.050000  ...  13.992  12.835  10.963  8.183   5.566

    September  October  November  December  Annual
22        NaN      NaN       NaN       NaN     NaN
23        NaN      NaN       NaN       NaN     NaN
24        NaN      NaN       NaN       NaN     NaN
25        NaN      NaN       NaN       NaN     NaN
26        NaN      NaN       NaN       NaN     NaN
..        ...      ...       ...       ...     ...
17      4.364    5.735     9.353    11.903  10.201
18      4.001    5.334     8.985    11.729  10.150
19      4.952    6.816     9.830    12.152  10.552
20      4.897    6.657     9.725    11.892  10.661
21      4.371    6.367       NaN       NaN  10.393

[144 rows x 33 columns]

### 2.2. Data Preprocessing

#### 2.2.1. Data Cleaning
Handle missing values, outliers, and other inconsistencies

#### 2.2.2. Data Transformation
Normalize, scale, or transform data as needed for analysis.

#### 2.2.3. Data Integration
Combine different datasets into a cohesive format.

## 3. Exploratory Data Analysis (EDA)

### 3.1. Initial Data Exploration
Use basic statistics and visualizations to understand the datasets.

### 3.2. Correlation Analysis

#### 3.2.1. Heatmaps
Visualize correlations between different environmental indicators.

#### 3.2.2. Geographic Heatmaps
Show spatial distribution of climate change indicators.

### 3.3. Time Series Analysis

#### 3.3.1. Line Plots
Examine trends in temperature and other variables over time.

#### 3.3.2. Seasonal Analysis
Investigate seasonal patterns in the data.

## 4. Data Visualization and Inference

### 4.1. Advanced Data Visualization

#### 4.1.1. Interactive Plots
Create dynamic plots for more engaging data exploration.

#### 4.1.2. Comparative Visualizations
Compare different indicators side-by-side

### 4.2. Inference from Visualizations
Draw conclusions from the visualizations created.

## 5. Predictive Modeling

### 5.1. Model Selection
Discuss the selection of predictive models

### 5.2. Model Training and Validation
Train models on historical data and validate their performance.

### 5.3. Forecasting
Use the models to forecast future climate trends based on historical data.

## 6. Discussion and Insights

### 6.1. Key Findings
Summarize the major insights gained from the analysis.

### 6.2. Unexpected Discoveries
Highlight any surprising patterns or results.

### 6.3. Limitations of the Study
Acknowledge any limitations in data or methodology.

## 7. Conclusion and Future Implications

### 7.1. Implications of Findings
Discuss how your findings impact our understanding of climate change.

### 7.2. Recommendations for Future Research
Suggest areas for further investigation.

### 7.3. Final Thoughts
Restate the importance of the project and its contributions to the field.

## 8. References

### 8.1. Data Sources
Cite the NASA datasets and any other sources used.

### 8.2. Additional Literature
Reference any additional literature that supported your analysis

## 9. Appendix

### 9.1. Additional Data
Include any supplementary data or analysis.

### 9.2. Code Documentation
Provide detailed comments and documentation for the code used.